In [1]:
"""Check system and GPU availability."""
import sys
import torch

print(f"Python: {sys.version}")
print(f"PyTorch: {torch.__version__}")
print(f"CUDA Available: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print(" No GPU - will be slower")

Python: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
PyTorch: 2.9.0+cu128
CUDA Available: True
GPU: Tesla T4
VRAM: 15.6 GB


In [2]:
# 1. Uninstall to prevent version conflicts
!pip uninstall -y torch torchvision torchaudio numpy pytorchvideo timm decord 

# 2. Install specific stable versions
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install "numpy>=1.26.4,<2.0"
#%pip install --force-reinstall numpy==1.26.4
!pip install git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f
!pip install timm==0.9.16 ftfy regex einops iopath decord openai-whisper librosa soundfile

print("\n")
print("RESTART RUNTIME NOW ")


Found existing installation: torch 2.9.0+cu128
Uninstalling torch-2.9.0+cu128:
  Successfully uninstalled torch-2.9.0+cu128
Found existing installation: torchvision 0.24.0+cu128
Uninstalling torchvision-0.24.0+cu128:
  Successfully uninstalled torchvision-0.24.0+cu128
Found existing installation: torchaudio 2.9.0+cu128
Uninstalling torchaudio-2.9.0+cu128:
  Successfully uninstalled torchaudio-2.9.0+cu128
Found existing installation: numpy 2.0.2
Uninstalling numpy-2.0.2:
  Successfully uninstalled numpy-2.0.2
Found existing installation: timm 1.0.24
Uninstalling timm-1.0.24:
  Successfully uninstalled timm-1.0.24
Looking in indexes: https://download.pytorch.org/whl/cu118
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 88.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 875.6/875.6 kB 64.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 118.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 663.9/663.9 M

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 193.1 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 97.1 MB/s eta 0:00:00:00:0100:01
  Attempting uninstall: numpy
    Found existing installation: numpy 2.3.5
    Uninstalling numpy-2.3.5:
      Successfully uninstalled numpy-2.3.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
pytensor 2.37.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have 

  Cloning https://github.com/facebookresearch/pytorchvideo.git (to revision 6cdc929315aab1b5674b6dcf73b16ec99147735f) to /tmp/pip-req-build-37kaz4rx
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorchvideo.git /tmp/pip-req-build-37kaz4rx
  Running command git rev-parse -q --verify 'sha^6cdc929315aab1b5674b6dcf73b16ec99147735f'
  Running command git fetch -q https://github.com/facebookresearch/pytorchvideo.git 6cdc929315aab1b5674b6dcf73b16ec99147735f
  Running command git checkout -q 6cdc929315aab1b5674b6dcf73b16ec99147735f
  Resolved https://github.com/facebookresearch/pytorchvideo.git to commit 6cdc929315aab1b5674b6dcf73b16ec99147735f
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 4.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━

In [1]:
# Verify
import numpy as np
import torch

print("Verifying installations:")
print(f"✓ NumPy: {np.__version__}")
print(f"✓ PyTorch: {torch.__version__}")
print(f"✓ CUDA Available: {torch.cuda.is_available()}")

# Check versions are correct
assert np.__version__.startswith('1.26'), f"Wrong numpy version: {np.__version__}"
assert torch.__version__.startswith('2.'), f"Wrong torch version: {torch.__version__}"



Verifying installations:
✓ NumPy: 1.26.4
✓ PyTorch: 2.7.1+cu118
✓ CUDA Available: True


In [9]:
"""Mount Google Drive and configure Python paths."""
from google.colab import drive
import sys
import os

drive.mount('/content/drive')

# Define paths
PROJECT_ROOT = "/content/drive/MyDrive/PFA"
IMAGEBIND_ROOT = os.path.join(PROJECT_ROOT, "ImageBind")
IMAGEBIND_REPO = os.path.join(IMAGEBIND_ROOT, "ImageBind")

# Create project root if doesn't exist
os.makedirs(PROJECT_ROOT, exist_ok=True)

sys.path.insert(0, IMAGEBIND_ROOT)      # ImageBind scripts
sys.path.insert(0, IMAGEBIND_REPO)      # imagebind library
sys.path.append(PROJECT_ROOT)           # shared_utils

print("✓ Drive mounted")
print(f"✓ Project root: {PROJECT_ROOT}")
print("\nPython search paths (in order):")
for i, p in enumerate(sys.path[:5]):
    print(f"  {i+1}. {p}")
print("✓ Paths configured correctly!")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✓ Drive mounted
✓ Project root: /content/drive/MyDrive/PFA

Python search paths (in order):
  1. /content/drive/MyDrive/PFA/ImageBind/ImageBind
  2. /content/drive/MyDrive/PFA/ImageBind
  3. /content
  4. /env/python
  5. /usr/lib/python312.zip
✓ Paths configured correctly!


In [10]:
# Verify the right scripts folder is found
scripts_path = os.path.join(IMAGEBIND_ROOT, "scripts/core")
if os.path.exists(scripts_path):
    print(f"✓ Found scripts at: {scripts_path}")
    files = os.listdir(scripts_path)
    print(f"  Files: {files}")
else:
    print(f"✗ Scripts not found at: {scripts_path}")

✓ Found scripts at: /content/drive/MyDrive/PFA/ImageBind/scripts/core
  Files: ['model_loader.py', 'embedding_engine.py', '__init__.py']


In [1]:
# Create the folders for scripts
import os

# Define Project Roots
PROJECT_ROOT = "/content/drive/MyDrive/PFA"
IMAGEBIND_PATH = os.path.join(PROJECT_ROOT, "ImageBind")

print("Creating folder structure...")

# 1. Folders to create
folder_map = [
    os.path.join(PROJECT_ROOT, "shared_utils"),
    os.path.join(PROJECT_ROOT, "data"),
    os.path.join(IMAGEBIND_PATH, "scripts/core"),
    os.path.join(IMAGEBIND_PATH, "scripts/utils"),
    os.path.join(IMAGEBIND_PATH, "results"),
    os.path.join(IMAGEBIND_PATH, "notebooks"),
    os.path.join(IMAGEBIND_PATH, "data")
]

for path in folder_map:
    os.makedirs(path, exist_ok=True)

print("✓ Folder structure created in Drive.")

# 2. Create __init__.py files
package_paths = [
    os.path.join(PROJECT_ROOT, "shared_utils"),
    os.path.join(IMAGEBIND_PATH, "scripts"),
    os.path.join(IMAGEBIND_PATH, "scripts/core"),
    os.path.join(IMAGEBIND_PATH, "scripts/utils")
]

for pkg_path in package_paths:
    init_file = os.path.join(pkg_path, "__init__.py")
    if not os.path.exists(init_file):
        with open(init_file, 'w') as f:
            f.write('"""\nPackage initialization\n"""\n')

print("✓ __init__.py files created.")
print("\n✓ Setup complete!")

Creating folder structure...
✓ Folder structure created in Drive.
✓ __init__.py files created.

✓ Setup complete!


In [7]:
import sys
import os

SCRIPTS_PARENT = "/content/drive/MyDrive/PFA/ImageBind"

if SCRIPTS_PARENT not in sys.path:
    # insert at 0 so it's checked first
    sys.path.insert(0, SCRIPTS_PARENT)
    print(f" Path Registered: {SCRIPTS_PARENT}")

In [9]:
import sys
import os

PROJECT_ROOT = "/content/drive/MyDrive/PFA"
IMAGEBIND_ROOT = os.path.join(PROJECT_ROOT, "ImageBind")


paths = [
    IMAGEBIND_ROOT,
    os.path.join(IMAGEBIND_ROOT, "ImageBind"),
    PROJECT_ROOT
]

for p in paths:
    if p not in sys.path:
        sys.path.insert(0, p)

print(" System paths synchronized.")

 System paths synchronized.


In [11]:
import sys
import os

# Define the absolute hierarchy based on your "Mon Drive" path
PROJECT_ROOT = "/content/drive/MyDrive/PFA"
OUTER_IMAGEBIND = os.path.join(PROJECT_ROOT, "ImageBind")
INNER_IMAGEBIND = os.path.join(OUTER_IMAGEBIND, "ImageBind") # This is where 'imagebind' package lives

# Add them to sys.path in order of importance
paths = [
    INNER_IMAGEBIND,  # 1. Finds the 'imagebind' library functions
    OUTER_IMAGEBIND,  # 2. Finds your 'scripts' folder
    PROJECT_ROOT      # 3. Finds 'shared_utils'
]

for p in paths:
    if p not in sys.path:
        sys.path.insert(0, p)
        print(f"✅ Added: {p}")

print("\n--- Testing Path Visibility ---")
print(f"Is 'scripts' visible? {os.path.exists(os.path.join(OUTER_IMAGEBIND, 'scripts'))}")
print(f"Is 'imagebind' pkg visible? {os.path.exists(os.path.join(INNER_IMAGEBIND, 'imagebind'))}")


--- Testing Path Visibility ---
Is 'scripts' visible? True
Is 'imagebind' pkg visible? True


In [1]:
import sys
import os

# 1. Define your Project Root (where shared_utils lives)
PROJECT_ROOT = "/content/drive/MyDrive/PFA"

# 2. Define the Script Root (where the scripts package lives)
# Based on your path: /content/drive/MyDrive/PFA/ImageBind
SCRIPTS_ROOT = "/content/drive/MyDrive/PFA/ImageBind"

# 3. Inject them into Python's memory
for path in [PROJECT_ROOT, SCRIPTS_ROOT]:
    if path not in sys.path:
        sys.path.insert(0, path)
        print(f" Linked: {path}")

# 4. Now, try the import again
try:
    from scripts.core import quick_load, create_engine
    print(" Success! Engine is now connected to shared_utils.")
except ModuleNotFoundError as e:
    # If it still fails, this will tell us exactly which file is missing
    import traceback
    print(f" Still missing a module: {e.name}")
    # We use traceback because the error is happening inside your files
    traceback.print_exc()

 Linked: /content/drive/MyDrive/PFA
 Linked: /content/drive/MyDrive/PFA/ImageBind
 Still missing a module: imagebind


Traceback (most recent call last):
  File "/tmp/ipython-input-695192941.py", line 19, in <cell line: 0>
    from scripts.core import quick_load, create_engine
  File "/content/drive/MyDrive/PFA/ImageBind/scripts/__init__.py", line 4, in <module>
    from . import core
  File "/content/drive/MyDrive/PFA/ImageBind/scripts/core/__init__.py", line 5, in <module>
    from .model_loader import (
  File "/content/drive/MyDrive/PFA/ImageBind/scripts/core/model_loader.py", line 7, in <module>
    from imagebind.models import imagebind_model
ModuleNotFoundError: No module named 'imagebind'


In [3]:
import sys
import os

# 1. The Root (for shared_utils)
PROJECT_ROOT = "/content/drive/MyDrive/PFA"

# 2. The Outer Folder (for your scripts)
SCRIPTS_ROOT = "/content/drive/MyDrive/PFA/ImageBind"

# 3. The Inner Folder (where the 'imagebind' library actually lives)
LIB_ROOT = "/content/drive/MyDrive/PFA/ImageBind/ImageBind"

# Inject all three in high-priority order
for p in [LIB_ROOT, SCRIPTS_ROOT, PROJECT_ROOT]:
    if p not in sys.path:
        sys.path.insert(0, p)
        print(f"✅ Linked: {p}")

print("\n--- Final Verification ---")
# Check if the library folder is actually there
if os.path.exists(os.path.join(LIB_ROOT, "imagebind")):
    print("💎 Found the ImageBind library folder!")
else:
    print("❌ Still can't see 'imagebind' folder. Check spelling in LIB_ROOT.")

✅ Linked: /content/drive/MyDrive/PFA/ImageBind/ImageBind

--- Final Verification ---
💎 Found the ImageBind library folder!


In [8]:
"""Load ImageBind and Whisper models."""

from scripts.core import quick_load, create_engine

print("Loading models...\n")

# Load models (downloads weights on first run)
imagebind, whisper, device = quick_load(whisper_size="base")

# Create embedding engine
engine = create_engine(imagebind, device, whisper)

print("\n✓ Engine ready for feature extraction!")

Loading models...

LOADING MODELS

✓ GPU available: Tesla T4
VRAM: 15.6 GB
Loading ImageBind-huge model...
This downloads ~1.2GB on first run (2-3 minutes)...



100%|██████████| 4.47G/4.47G [00:44<00:00, 108MB/s] 


✓ ImageBind model loaded successfully!
Device: cuda:0
GPU Memory Used: 4.88 GB
Loading Whisper model (size: base)...


100%|████████████████████████████████████████| 139M/139M [00:00<00:00, 150MiB/s]


✓ Whisper-base loaded successfully!

✓ All models loaded successfully!

✓ Engine ready for feature extraction!


Test

In [11]:
"""Test that ImageBind is working correctly."""
import torch
import numpy as np
from imagebind.models.imagebind_model import ModalityType
from imagebind import data

print("Running validation test...\n")

try:
    # Test with text embeddings
    text_list = [
        "A dramatic moment",
        "Crowd cheering loudly",
        "A funny scene",
        "An emotional speech"
    ]
    
    inputs = {
        ModalityType.TEXT: data.load_and_transform_text(text_list, device)
    }
    
    with torch.no_grad():
        embeddings = imagebind(inputs)
    
    text_embeddings = embeddings[ModalityType.TEXT]
    
    print(f"✓ Text embeddings shape: {text_embeddings.shape}")
    print(f"✓ Embedding dimension: {text_embeddings.shape[1]}")
    
    # Compute similarity
    similarity = torch.softmax(text_embeddings @ text_embeddings.T, dim=-1)
    print(f"\n✓ Similarity matrix computed")
    print(similarity.cpu().numpy())
    
    print("\n✓ ImageBind validation passed!")
    print("✓ Setup complete! Ready to extract features.")

except Exception as e:
    print(f"✗ Validation failed: {e}")
    print("Check that all dependencies are installed correctly.")

Running validation test...

✓ Text embeddings shape: torch.Size([4, 1024])
✓ Embedding dimension: 1024

✓ Similarity matrix computed
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

✓ ImageBind validation passed!
✓ Setup complete! Ready to extract features.
